---
- name: systemd | ansibot | install ansible-pull service
  tags: ansibot,systemd,automation
  become: true
  ansible.builtin.copy:
    src: files/systemd/ansible-pull.service   # Service unit in repo
    dest: /etc/systemd/system/ansible-pull.service
    owner: ansibot
    group: ansibot
    mode: '0644'

- name: systemd | ansibot | install ansible-pull timer
  tags: ansibot,systemd,automation
  become: true
  ansible.builtin.copy:
    src: files/systemd/ansible-pull.timer     # Timer unit in repo
    dest: /etc/systemd/system/ansible-pull.timer
    owner: ansibot
    group: ansibot
    mode: '0644'

- name: systemd | ansibot | reload systemd to pick up new units
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: systemd | ansibot | enable and start ansible-pull timer
  become: true
  ansible.builtin.systemd:
    name: ansible-pull.timer
    enabled: true
    state: started
