---
- name: Apply common configuration
  hosts: all                         # Matches all hosts in inventory
  become: true
  roles:
    - common                         # Apply the common role to every host
