---
- name: Apply common configuration        # First play: baseline setup for all hosts
  hosts: all                              # Target every host in inventory
  become: true                            # Run tasks with sudo
  roles:                                  # Roles to apply
    - common                              # Common role: base system config
    
- name: Configure hosts/group machines    # Second play: specific to target
  hosts:                                  # Target hosts and groups
    -                                     # List of hosts & groups
  become: true                            # Run tasks with sudo
  roles:                                  # Apply these roles
    -                                     # List of Roles
