---
- name: users | ansibot | create ansibot group
  tags: always,ansibot,users
  ansible.builtin.group:
    name: ansibot
    state: present

- name: users | ansibot | create ansibot system user (with working dir as home)
  tags: always,ansibot,users
  ansible.builtin.user:
    name: ansibot
    group: ansibot                  # primary group
    system: true                    # system account (UID < 1000)
    shell: /usr/sbin/nologin        # disable login
    home: /var/lib/ansibot          # working dir as home
    create_home: true              # don’t auto-create home
    state: present

- name: users | ansibot | working directory
  tags: ansibot,users
  ansible.builtin.file:
    path: /var/lib/ansibot          # ansibot working dir
    state: directory
    owner: ansibot
    group: ansibot
    mode: '0770'

- name: users | ansibot | ensure ansible temp dir exists
  tags: ansibot,users
  ansible.builtin.file:
    path: /home/ansibot/.ansible/tmp
    state: directory
    owner: ansibot
    group: ansibot
    mode: '0770'

- name: users | ansibot | temhr | add to ansibot group
  tags: temhr,ansibot,users
  ansible.builtin.user:
    name: temhr
    groups: ansibot                 # add supplementary group
    append: true                    # preserve existing groups

- name: users | ansibot | add sudoers file
  tags: settings,ansibot,sudo,system,users
  ansible.builtin.copy:
    dest: /etc/sudoers.d/ansibot
    owner: root
    group: root
    mode: '0440'                    # required for sudoers
    content: |
      ansibot ALL=(ALL) NOPASSWD:ALL
