---
- name: users | ansibot | create ansibot system user (no home)
  tags: always
  ansible.builtin.user:
    name: ansibot                                               # Username = "ansibot"
    group: ansibot                                              # Assign to primary group "ansibot" (must exist or be created)
    system: true                                                # Mark as a system account (UID < 1000, for services)
    shell: /usr/sbin/nologin                                    # No login shell, prevents interactive logins
    create_home: false                                          # Do NOT create a home directory
    state: present                                              # Ensure the user exists (idempotent)

- name: users | ansibot | add sudoers file
  tags: settings,ansibot,sudo,system,users
  ansible.builtin.copy:
    src: files/users/sudoers_ansibot                            # Source file in repo with sudo rules
    dest: /etc/sudoers.d/ansibot                                # Install into system sudoers directory
    owner: root                                                 # File owned by root
    group: root                                                 # Group owned by root
    mode: '0440'                                                # Read-only, required for sudoers

- name: users | ansibot | working directory
  tags: ansibot,users
  ansible.builtin.file:                                         # Use the "file" module to manage directories
    path: /var/lib/ansibot                                      # Path where ansibot stores files (service convention)
    state: directory                                            # Ensure it's a directory
    owner: ansibot                                              # Owned by ansibot user
    group: ansibot                                              # Owned by ansibot group
    mode: '0750'                                                # Only ansibot+group can enter, others denied
