---
# Main task list for baseline setup
- block:
  # Ensure users' existence
  - ansible.builtin.import_tasks: users/temhr.yml
  - ansible.builtin.import_tasks: users/ansibot.yml

  # Setup the ansible environment
  - ansible.builtin.import_tasks: systemd/ansible-pull.yml
