---
# Main task list for baseline setup
- block:
  # Ensure users' existence
  - ansible.builtin.import_tasks: users/temhr.yml
  - ansible.builtin.import_tasks: users/ansibot.yml

  # Setup the ansible environment
  - ansible.builtin.import_tasks: systemd/ansible-pull.yml
  
  rescue:
    - name: Log the error and continue
      ansible.builtin.debug:
        msg: "A task in this block failed, but playbook continues."
