- name: packages | utilities | install packages
  tags: packages,utilities,install
  ansible.builtin.package:
    state: latest
    name:
      - adb
      - at
      - bat
      - busybox
      - colordiff
      - cron
      - curl
      - ethtool
      - fastfetch
      - fzf
      - gcc
      - git
      - htop
      - iperf
      - iotop
      - lsof
      - mc
      - nala
      - ncdu
      - net-tools
      - nmap
      - ranger
      - rsync
      - screen
      - sshfs
      - sudo
      - tmux
      - traceroute
      - usbutils
      - vim
      - wget
      - whois
      - zoxide
